RIA-8271 Print and send hearing requirements form
hmcts/ia-task-configuration pull request #407
Opened 2024-05-09 12:18 UTC by javierhmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-8271

### Change description ###

Print and send hearing requirements form WA-TASK

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2024-05-10 08:45 UTC, ThomasKKC requested changes

2024-05-10 08:45 UTC, ThomasKKC commented on src/main/resources/wa-task-configuration-ia-asylum.dmn
> +                       "printAndSendHoBundle", "printAndSendHearingRequirements"
For easier to rebase in the future, can you add this on the next line? Follow the format above

2024-05-10 08:45 UTC, ThomasKKC commented on src/main/resources/wa-task-configuration-ia-asylum.dmn
> +"printAndSendHoBundle", "printAndSendHearingRequirements"</text>
For easier to rebase in the future, can you add this on the next line? Follow the format above

2024-05-10 08:45 UTC, ThomasKKC commented on src/main/resources/wa-task-initiation-ia-asylum.dmn
> +          <text>"requestHearingRequirements"</text>
Think this is the wrong event id, and now redundant. Can you please check.

2024-05-10 08:48 UTC, ThomasKKC requested changes

2024-05-10 08:48 UTC, ThomasKKC commented on src/main/resources/wa-task-initiation-ia-asylum.dmn
> +          <text>true</text>
Can you make sure this is published on the event?

2024-05-13 08:37 UTC, ThomasKKC approved these changes

2024-05-14 16:02 UTC, colmlynch60 reviewed
LGTM

2024-05-14 16:02 UTC, merged