RIA-8273 Print and send hearing bundle - WA TASK
hmcts/ia-task-configuration pull request #412
Opened 2024-05-14 15:45 UTC by javierhmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RIA-8273

### Change description ###

 Print and send hearing bundle - WA TASK

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2024-05-14 16:09 UTC, ThomasKKC requested changes

2024-05-14 16:09 UTC, ThomasKKC commented on src/main/resources/wa-task-initiation-ia-asylum.dmn
> +          <text>"generateHearingBundle"</text>
I think asyncStitchingComplete is the event to use for this scenario.

2024-05-14 16:09 UTC, ThomasKKC commented on src/main/resources/wa-task-initiation-ia-asylum.dmn
> +          <text>true</text>
Need to publish this isAdmin too.

2024-05-15 11:07 UTC, ThomasKKC requested changes

2024-05-15 11:07 UTC, ThomasKKC commented on src/main/resources/wa-task-initiation-ia-asylum.dmn
> +          <text>"finalBundling"</text>
We need to post event state, not pre event state. Please check AdvancedFinalBundlingStateHandler

2024-05-16 15:57 UTC, ThomasKKC approved these changes

2024-05-17 08:22 UTC, colmlynch60 approved these changes
LGTM

2024-05-17 08:22 UTC, merged